volumes:
  production_kisune_postgres_data: {}
  production_kisune_postgres_data_backups: {}
  production_kisune_mongo_data: {}

services:
  postgres-db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: production-kisune-postgres
    volumes:
      - production_kisune_postgres_data:/var/lib/postgresql/data
      - production_kisune_postgres_data_backups:/backups
    env_file: ./.env
    ports:
      - "5432:5432"
    container_name: postgres
  
  mongo-db:
    image: mongo:7.0.1
    volumes:
      - local_kisune_mongo_data:/data/db
    env_file: ./.env
    ports:
      - "27017:27017"
    container_name: mongodb

  auth-service:
    build:
      context: .
      dockerfile: ./compose/local/auth-service/Dockerfile
    image: local-kisune-auth-service
    volumes:
      - ./auth-service:/auth-service
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start
    container_name: auth-service
    depends_on:
      - postgres-db

  chat-service:
    build:
      context: .
      dockerfile: ./compose/local/chat-service/Dockerfile
    image: local-kisune-chat-service
    volumes:
      - ./chat-service:/chat-service
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    command: /start
    container_name: chat-service
    depends_on:
      - auth-service
